services:

  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "2400:2400"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mcp_server